--CREATE DATABASE OrchidFashionHouse

--USE OrchidFashionHouse


CREATE TABLE SUPPLIER
(
SupplierId INT IDENTITY(1001,1) PRIMARY KEY,
SUPPLIERNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
PHONENUMBER INT NOT NULL,
PRODUCTNAME VARCHAR(50) NOT NULL,
PRODUCTTYPE VARCHAR(50) NOT NULL,
QUANTITY INT NOT NULL,
SIZE INT NOT NULL,
DATE DATE NOT NULL,
PRICE INT NOT NULL
);
drop table SUPPLIER

INSERT INTO SUPPLIER VALUES('Beck','beck9@gmail.com','Dhaka',01744589881,'saree','cotton',2,34,'12-8-2023', 3000);
INSERT INTO SUPPLIER VALUES('Rose','rose@gmail.com','Rajshahi',01747789971,'shirt','cotton',5,32,'1-7-2023', 10000);
INSERT INTO SUPPLIER VALUES('Natalie','natalie88@gmail.com','Khulna',01756789971,'tops','silk',3,36,'12-9-2023', 7000);
select * from SUPPLIER


CREATE TABLE ORDERS
(
ORDERID int IDENTITY(6001,1) PRIMARY KEY,
PRODUCTNAME varchar(50) NOT NULL,
QUANTITY INT NOT NULL,
SIZE INT NOT NULL,
DATE DATE NOT NULL,
PRICE INT NOT NULL
);
DROP TABLE ORDERS

INSERT INTO ORDERS VALUES('Shirt',3,34,'2023-5-3',5000);
INSERT INTO ORDERS VALUES('Skirt',3,34,'2023-4-5',7000);
INSERT INTO ORDERS VALUES('Saree',3,34,'2023-2-7',1000);
select* from orders


CREATE TABLE CUSTOMER
(
CUSTOMERID int IDENTITY(5001,1) PRIMARY KEY,
CUSTOMERNAME varchar(150) NOT NULL,
ADDRESS varchar(200) NOT NULL,
PHONENUMBER varchar(11) NOT NULL UNIQUE,
EMAIL varchar(50) NOT NULL, 
);
Drop table CUSTOMER
INSERT INTO CUSTOMER VALUES('WALTER','RAJSHAHI','01799567893','walter99@gmail.com');
INSERT INTO CUSTOMER VALUES('TONY','DHAKA','01799555963','tony6@gmail.com');
INSERT INTO CUSTOMER VALUES('JOE','DHAKA','01767946963','joe5@gmail.com');
select* from CUSTOMER


CREATE TABLE BILLING
(
BILLINGID int IDENTITY(9001,1) PRIMARY KEY,
PRODUCTNAME varchar(150) NOT NULL,
QUANTITY INT NOT NULL,
SIZE INT NOT NULL,
DATE DATE NOT NULL ,
TIME TIME NOT NULL,
PRICE varchar(150) NOT NULL
);
drop table BILLING

INSERT INTO BILLING VALUES('Panjabi',2,34,'12-2-2023','12:15',4000);
select* from BILLING


CREATE TABLE MEN
(
MENPRID int IDENTITY(3001,1) PRIMARY KEY,
PRODUCTNAME varchar(150) NOT NULL,
PRODUCTTYPE varchar(200)  NULL,
QUANTITY INT NOT NULL,
SIZE INT NOT NULL,
PRICE varchar(150) NOT NULL
);
DROP TABLE MEN

INSERT INTO MEN VALUES('T-shirt','Cotton',5,32,3000);
INSERT INTO MEN VALUES('Panjabi','Cotton',3,34,10000);
INSERT INTO MEN VALUES('Shirt','Cotton',2,32,3000);

select* from MEN


CREATE TABLE WOMEN
(
WOMENPRID int IDENTITY(4001,1) PRIMARY KEY,
PRODUCTNAME varchar(150) NOT NULL,
PRODUCTTYPE varchar(200)  NULL,
QUANTITY INT NOT NULL,
SIZE INT NOT NULL,
PRICE varchar(150) NOT NULL
);
drop table WOMEN

INSERT INTO WOMEN VALUES('shirt','cotton',3,34,5000);
INSERT INTO WOMEN VALUES('saree','cotton',1,40,4000);
INSERT INTO WOMEN VALUES('selwar kamiz','lilen',4,38,6000);

select* from WOMEN


CREATE TABLE CHILDREN
(
CHILDRENPRID int IDENTITY(7001,1) PRIMARY KEY,
PRODUCTNAME varchar(150) NOT NULL,
PRODUCTTYPE varchar(200)  NULL,
QUANTITY INT NOT NULL,
SIZE INT NOT NULL,
PRICE varchar(150) NOT NULL
);
DROP TABLE CHILDREN

INSERT INTO CHILDREN VALUES('tops','Cotton',3,22,4000);
INSERT INTO CHILDREN VALUES('shirt','Cotton',3,26,4000);
INSERT INTO CHILDREN VALUES('pant','Cotton',3,22,9000);

select* from CHILDREN

delete from customer where customerid= 5007
select * from customer