/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orchidboutiquehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
     Connection con;
    //PreparedStatement pre = null;
    PreparedStatement pre;
    ResultSet res = null;
    public Billing() {
        initComponents();
        showAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        tAmount = new javax.swing.JTextField();
        paidamount = new javax.swing.JTextField();
        proName = new javax.swing.JTextField();
        proName5 = new javax.swing.JTextField();
        proName6 = new javax.swing.JTextField();
        returnamount = new javax.swing.JTextField();
        billingId = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        BilTtxt = new javax.swing.JTextArea();
        Print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        JLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orchid Fashion House");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 220, -1));

        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });
        getContentPane().add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 220, -1));

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 220, 220, -1));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 220, -1));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 50, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Customerer Id", "Quantity", "Time", "Date", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 690, 240));

        add.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(204, 153, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, -1, -1));

        update.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(204, 153, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, -1, -1));

        tAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAmountActionPerformed(evt);
            }
        });
        getContentPane().add(tAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 270, 220, -1));

        paidamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidamountActionPerformed(evt);
            }
        });
        getContentPane().add(paidamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, 210, 20));

        proName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proNameActionPerformed(evt);
            }
        });
        getContentPane().add(proName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 210, 20));

        proName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proName5ActionPerformed(evt);
            }
        });
        getContentPane().add(proName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 210, 20));

        proName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proName6ActionPerformed(evt);
            }
        });
        getContentPane().add(proName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 210, 20));

        returnamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnamountActionPerformed(evt);
            }
        });
        getContentPane().add(returnamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 370, 210, 20));

        billingId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingIdActionPerformed(evt);
            }
        });
        getContentPane().add(billingId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 210, 20));

        type.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        type.setForeground(new java.awt.Color(204, 153, 255));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Men", "Women", "Children", " ", " " }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, 30));

        BilTtxt.setBackground(new java.awt.Color(240, 240, 240));
        BilTtxt.setColumns(20);
        BilTtxt.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        BilTtxt.setForeground(new java.awt.Color(102, 0, 102));
        BilTtxt.setRows(5);
        BilTtxt.setText("\t                ****************ORCHID FASHION HOUSE****************\t\n        \t     \n");
        jScrollPane2.setViewportView(BilTtxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 430, 180));

        Print.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Print.setForeground(new java.awt.Color(204, 153, 255));
        Print.setText("PRINT");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        getContentPane().add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 670, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BILL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 430, 60, -1));

        add1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        add1.setForeground(new java.awt.Color(204, 153, 255));
        add1.setText("Add");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, -1, -1));

        delete1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        delete1.setForeground(new java.awt.Color(204, 153, 255));
        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 700, -1, -1));

        JLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/billing.jpg"))); // NOI18N
        getContentPane().add(JLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
            Connection connection = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                     +"encrypt=true;trustServerCertificate=true;"
                    + "selectMethod=cursor;", "sa", "123456" ); 
String query = "insert into Billing(ProductName, Quantity, Size, Date, Time, TotalAmount, PaidAmount, ReturnAmount ) values (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, proName.getText());
            pst.setString(2, quantity.getText());
            pst.setString(3, size.getText());
            pst.setString(4, date.getText());
            pst.setString(5, time.getText());
            pst.setString(6, tAmount.getText());
            pst.setString(7, paidamount.getText());
            pst.setString(8, returnamount.getText());


            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration Successfull!");
            
            showAll();

        }
        catch (Exception e) 
            
        { e.printStackTrace();

    }
    }//GEN-LAST:event_addActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new pages().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void tAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAmountActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       //String Category = (String)category.getSelectedItem();
        
        int ID = Integer.parseInt(billingId.getText());
        String ProductName = proName.getText();
        //String type = protype.getText();
        int Quantity = Integer.parseInt(quantity.getText());
        String Size = size.getText();
        String TotalAmount = tAmount.getText();
        String PaidAmount = paidamount.getText();
        String ReturnAmount = returnamount.getText();
        

        try {
        String sql = "UPDATE BILLING set  PRODUCTNAME="+ProductName+",QUANTITY = "+Quantity+", SIZE = "+Size+", TOTALAMOUNT = "+TotalAmount+", PAIDAMOUNT = "+PaidAmount+", RETURNAMOUNT = "+ReturnAmount+" WHERE BILLINGID= "+ID;
        Statement st = con.createStatement();
        int row = st.executeUpdate(sql);

       

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        
        }
        showAll();
        billingId.setText(null);
        proName.setText(null);
        //protype.setText(null);
        quantity.setText(null);
        size.setText(null);
        tAmount.setText(null);
        paidamount.setText(null);
        returnamount.setText(null);
     // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void paidamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidamountActionPerformed

    private void proNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proNameActionPerformed

    private void proName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proName5ActionPerformed

    private void proName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proName6ActionPerformed

    private void returnamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnamountActionPerformed

    private void billingIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billingIdActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed
 int i = 0;
    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
     
        float ret;
        ret = Float.valueOf(tAmount.getText()) - Float.valueOf(paidamount.getText());
        if(proName.getText().isEmpty() || quantity.getText().isEmpty() || tAmount.getText().isEmpty() || paidamount.getText().isEmpty() )
     {
         JOptionPane.showMessageDialog(this, "Missing Information");
     }
     else{
         i++;
     if(i==1)
     {
        BilTtxt.setText("	                ****************ORCHID FASHION HOUSE****************\n\t "+
             " \tID    PRODUCT NAME    QUANTITY    TOTAL AMOUNT    PAID AMOUNT    RETURN AMOUNT\n\t"
        +"                           "+i+"             "+proName.getText()+"                       "+quantity.getText() +"                        "+tAmount.getText()+"                           "+paidamount.getText()+"                      "+Float.toString(ret)+"\n                      ");
     }
     else
     { 
         BilTtxt.setText(BilTtxt.getText()             +i+"          "+proName.getText()+"                           "+quantity.getText() +"                          "+tAmount.getText()+"                             "+paidamount.getText()+"                                 "+Float.toString(ret));
     }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_add1ActionPerformed
    

    }
    
    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try{
            BilTtxt.print();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
                        // TODO add your handling code here:
    }//GEN-LAST:event_PrintActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete1ActionPerformed

 private void showAll() {
        try {
            con = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                     +"encrypt=true;trustServerCertificate=true;"
                    + "selectMethod=cursor;", "sa", "123456" ); 
            pre = con.prepareStatement("select * from BILLING");
            res = pre.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
        } catch (SQLException ex) {
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BilTtxt;
    private javax.swing.JLabel JLabel1;
    private javax.swing.JButton Print;
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JLabel back;
    private javax.swing.JTextField billingId;
    private javax.swing.JTextField date;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField paidamount;
    private javax.swing.JTextField proName;
    private javax.swing.JTextField proName5;
    private javax.swing.JTextField proName6;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField returnamount;
    private javax.swing.JTextField size;
    private javax.swing.JTextField tAmount;
    private javax.swing.JTextField time;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
