/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orchidboutiquehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Children extends javax.swing.JFrame {

    /**
     * Creates new form Children
     */
      Connection con;
    //PreparedStatement pre = null;
    PreparedStatement pre;
    ResultSet res = null;
    public Children() {
        initComponents();
        showAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        category = new javax.swing.JComboBox<>();
        childproid = new javax.swing.JTextField();
        protype = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        Size = new javax.swing.JTextField();
        proName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orchid Fashion House");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Supplier Id", "Quantity", "Size", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 670, 380));

        category.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        category.setForeground(new java.awt.Color(204, 153, 255));
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selwar Kamiz  ", "Tops", "Skirt", "Ladies shirt", "Ladies Jeans", "Panjabi", "Payjama", "Shirt", "Pant", "T-shirt", "Jeans" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        getContentPane().add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 30));

        childproid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childproidActionPerformed(evt);
            }
        });
        getContentPane().add(childproid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 245, 180, 30));

        protype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protypeActionPerformed(evt);
            }
        });
        getContentPane().add(protype, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 327, 180, 30));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 365, 180, 30));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 445, 180, 30));

        add.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(204, 153, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        update.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(204, 153, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        delete.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(204, 153, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 50, 50));

        Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeActionPerformed(evt);
            }
        });
        getContentPane().add(Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 404, 180, 30));
        getContentPane().add(proName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 285, 180, 30));

        jButton2.setForeground(new java.awt.Color(204, 153, 255));
        jButton2.setText("FILTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 30));

        jButton3.setForeground(new java.awt.Color(204, 153, 255));
        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/children.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void protypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protypeActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
            Connection connection = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                     +"encrypt=true;trustServerCertificate=true;"
                    + "selectMethod=cursor;", "sa", "123456" ); 
String query = "insert into Children(ProductName, ProductType, Quantity, Size, Price ) values (?,?,?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, proName.getText());
            pst.setString(2, protype.getText());
            pst.setString(3, quantity.getText());
            pst.setString(4, Size.getText());
            pst.setString(5, price.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration Successfull!");
            showAll();

        }
        catch (Exception e) 
            
        { e.printStackTrace();

    }        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeActionPerformed
    }//GEN-LAST:event_SizeActionPerformed
private void showAll() {
        try {
            con = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                     +"encrypt=true;trustServerCertificate=true;"
                    + "selectMethod=cursor;", "sa", "123456" ); 
            pre = con.prepareStatement("select * from CHILDREN");
            res = pre.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
        } catch (SQLException ex) {
        }
    
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String Category = (String)category.getSelectedItem();
            con = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                +"encrypt=true;trustServerCertificate=true;"
                + "selectMethod=cursor;", "sa", "123456" );

            pre = con.prepareStatement("select * from CHILDREN where PRODUCTNAME = '"+Category+"'");
            res = pre.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String Category = (String)category.getSelectedItem();
            con = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                +"encrypt=true;trustServerCertificate=true;"
                + "selectMethod=cursor;", "sa", "123456" );

            pre = con.prepareStatement("select * from CHILDREN");
            res = pre.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        //String Category = (String)category.getSelectedItem();
        
        int ID = Integer.parseInt(childproid.getText());
        String name = proName.getText();
        String type = protype.getText();
        int Quantity = Integer.parseInt(quantity.getText());
        String size = Size.getText();
        String Price = price.getText();
        try {
        String sql = "UPDATE CHILDREN set QUANTITY = "+Quantity+",SIZE = "+size+", PRICE = "+Price+" WHERE CHILDRENPRID= "+ID;
        Statement st = con.createStatement();
        int row = st.executeUpdate(sql);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        
        }
        showAll();
        childproid.setText(null);
        proName.setText(null);
        protype.setText(null);
        quantity.setText(null);
        Size.setText(null);
        price.setText(null);
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      try {
            int ID = Integer.parseInt(childproid.getText());

            String sql = "DELETE from CHILDREN where CHILDRENPRID = " +ID;
            Statement st = con.createStatement();
            int row = st.executeUpdate(sql);
            
            showAll();
            childproid.setText("");
            proName.setText("");
            protype.setText("");
            quantity.setText("");
            Size.setText("");
            price.setText("");

        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void childproidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childproidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childproidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Children.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Children.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Children.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Children.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Children().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Size;
    private javax.swing.JButton add;
    private javax.swing.JLabel back;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField childproid;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField proName;
    private javax.swing.JTextField protype;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
