/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orchidboutiquehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    //Connection con = null;
    Connection con;
    //PreparedStatement pre = null;
    PreparedStatement pre;
    ResultSet res = null;
    public Supplier() {
        initComponents();
        showAll();
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phnno = new javax.swing.JTextField();
        protype = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        address = new javax.swing.JTextField();
        proname = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        supplierName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id = new javax.swing.JComboBox<>();
        supplierid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orchid Fashion House");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnnoActionPerformed(evt);
            }
        });
        getContentPane().add(phnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 260, -1));

        protype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protypeActionPerformed(evt);
            }
        });
        getContentPane().add(protype, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 260, -1));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 260, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 260, -1));

        add.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(204, 153, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, -1, 20));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 50, 50));

        update.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(204, 153, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, -1));

        delete.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(204, 153, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Supplier Id", "Product Id", "Supplier Name", "Address", "E-mail", "Quantity", "Size", "Date", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 670, 360));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 260, -1));

        proname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronameActionPerformed(evt);
            }
        });
        getContentPane().add(proname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 260, -1));

        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });
        getContentPane().add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 260, -1));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 260, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 260, -1));

        supplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameActionPerformed(evt);
            }
        });
        getContentPane().add(supplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 260, -1));

        jButton2.setForeground(new java.awt.Color(204, 153, 255));
        jButton2.setText("FILTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, -1, 30));

        jButton3.setForeground(new java.awt.Color(204, 153, 255));
        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, -1, 30));

        id.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(204, 153, 255));
        id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Men", "Women", "Children", " " }));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, 30));

        supplierid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplieridActionPerformed(evt);
            }
        });
        getContentPane().add(supplierid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supplier.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnnoActionPerformed

    private void protypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protypeActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     try{
         String type = (String)id.getSelectedItem();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
            Connection connection = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                     +"encrypt=true;trustServerCertificate=true;"
                    + "selectMethod=cursor;", "sa", "123456" ); 
            
            if(type.equals("Men")){
                String Mquery = "insert into Men(ProductName,ProductType, Quantity, Size, Price ) values (?,?,?,?,?)";
                PreparedStatement Mpst = connection.prepareStatement(Mquery);
                Mpst.setString(1, proname.getText());
                Mpst.setString(2, protype.getText());
                Mpst.setString(3, quantity.getText());
                Mpst.setString(4, size.getText());
                Mpst.setString(5, price.getText());
                
                Mpst.executeUpdate();
                
            String query = "insert into Supplier(SupplierName,Email, Address, PhoneNumber,ProductName,ProductType, Quantity, Size, Date, Price ) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, supplierName.getText());
            pst.setString(2, Email.getText());
            pst.setString(3, address.getText());
            pst.setString(4, phnno.getText());
            pst.setString(5, proname.getText());
            pst.setString(6, protype.getText());
            pst.setString(7, quantity.getText());
            pst.setString(8, size.getText());
            pst.setString(9, date.getText());
            pst.setString(10, price.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration Successfull!");
            }
            else if(type.equals("Women")){
                String Mquery = "insert into Women(ProductName,ProductType, Quantity, Size, Price ) values (?,?,?,?,?)";
                PreparedStatement Mpst = connection.prepareStatement(Mquery);
                Mpst.setString(1, proname.getText());
                Mpst.setString(2, protype.getText());
                Mpst.setString(3, quantity.getText());
                Mpst.setString(4, size.getText());
                Mpst.setString(5, price.getText());
                
                Mpst.executeUpdate();
                
            String query = "insert into Supplier(SupplierName,Email, Address, PhoneNumber,ProductName,ProductType, Quantity, Size, Date, Price ) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, supplierName.getText());
            pst.setString(2, Email.getText());
            pst.setString(3, address.getText());
            pst.setString(4, phnno.getText());
            pst.setString(5, proname.getText());
            pst.setString(6, protype.getText());
            pst.setString(7, quantity.getText());
            pst.setString(8, size.getText());
            pst.setString(9, date.getText());
            pst.setString(10, price.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration Successfull!");
            }
            
            else if(type.equals("Children")){
                String Mquery = "insert into Children(ProductName,ProductType, Quantity, Size, Price ) values (?,?,?,?,?)";
                PreparedStatement Mpst = connection.prepareStatement(Mquery);
                Mpst.setString(1, proname.getText());
                Mpst.setString(2, protype.getText());
                Mpst.setString(3, quantity.getText());
                Mpst.setString(4, size.getText());
                Mpst.setString(5, price.getText());
                
                Mpst.executeUpdate();
                
            String query = "insert into Supplier(SupplierName,Email, Address, PhoneNumber,ProductName,ProductType, Quantity, Size, Date, Price ) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, supplierName.getText());
            pst.setString(2, Email.getText());
            pst.setString(3, address.getText());
            pst.setString(4, phnno.getText());
            pst.setString(5, proname.getText());
            pst.setString(6, protype.getText());
            pst.setString(7, quantity.getText());
            pst.setString(8, size.getText());
            pst.setString(9, date.getText());
            pst.setString(10, price.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration Successfull!");
            }
            
            
            showAll();
        }
        catch (Exception e) 
        
        { e.printStackTrace();

    }
     // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

        private void showAll() {
        try {
            con = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                     +"encrypt=true;trustServerCertificate=true;"
                    + "selectMethod=cursor;", "sa", "123456" ); 
            pre = con.prepareStatement("select * from SUPPLIER");
            res = pre.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
        } catch (SQLException ex) {
        }
    
    }

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new pages().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        //String Category = (String)category.getSelectedItem();
        
        int ID = Integer.parseInt(supplierid.getText());
        String name = proname.getText();
        String type = protype.getText();
        int Quantity = Integer.parseInt(quantity.getText());
        String Size = size.getText();
        String Price = price.getText();
        try {
        String sql = "UPDATE SUPPLIER set QUANTITY = "+Quantity+",SIZE = "+Size+", PRICE = "+Price+" WHERE SUPPLIERID= "+ID;
        Statement st = con.createStatement();
        int row = st.executeUpdate(sql);

       
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        
        }
        showAll();
        supplierid.setText(null);
        proname.setText(null);
        protype.setText(null);
        quantity.setText(null);
        size.setText(null);
        price.setText(null);
    }//GEN-LAST:event_updateActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void pronameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronameActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
         
    }//GEN-LAST:event_dateActionPerformed

    private void supplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            //String id = (String)id.getSelectedItem();
            con = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                +"encrypt=true;trustServerCertificate=true;"
                + "selectMethod=cursor;", "sa", "123456" );

            pre = con.prepareStatement("select * from SUPPLIER where PRODUCTNAME = '"+id+"'");
            res = pre.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String Category = (String)id.getSelectedItem();
            con = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;databaseName=OrchidFashionHouse;"
                +"encrypt=true;trustServerCertificate=true;"
                + "selectMethod=cursor;", "sa", "123456" );

                pre = con.prepareStatement("select * from SUPPLIER");
            res = pre.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     try {
            int ID = Integer.parseInt(supplierid.getText());

            String sql = "DELETE from SUPPLIER where SUPPLIERID = " +ID;
            Statement st = con.createStatement();
            int row = st.executeUpdate(sql);
            
            showAll();
            proname.setText("");
            protype.setText("");
            quantity.setText("");
            size.setText("");
            price.setText("");

        } catch (SQLException ex) {
            
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void supplieridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplieridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplieridActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JLabel back;
    private javax.swing.JTextField date;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField phnno;
    private javax.swing.JTextField price;
    private javax.swing.JTextField proname;
    private javax.swing.JTextField protype;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField size;
    private javax.swing.JTextField supplierName;
    private javax.swing.JTextField supplierid;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables


}
